kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: angular-demo
  namespace: test
  labels:
    k8s-app: angular-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: angular-demo
  template:
    metadata:
      labels:
        k8s-app: angular-demo
        name: angular-demo
    spec: 
      nodeSelector:
        nodeRole: ms 
        
      containers:
        - image: docker.registry.cscloud.com/angulardemo
          name: angular-demo
          imagePullPolicy: Always   
          ports:
            - containerPort: 4200 
       
---
apiVersion: v1
kind: Service
metadata:
  name: angular-demo
  namespace: test
spec:
  selector:
    k8s-app: angular-demo
  ports:
  - port: 4200
    targetPort: 4200
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: angular-demo
  namespace: test
spec:
  rules:
  - host: angular.demo.cscloud.com
    http:
      paths:
        - path: 
          backend:
            serviceName: angular-demo
            servicePort: 4200            