#!/bin/sh

## npm config set registry https://registry.npm.taobao.org  
## npm uninstall -g angular-cli  
## npm cache clean  --force
## yum install python
## npm install -g typescript typings 
## npm install -g @anguluar/cli

git pull

docker rmi -f angulardemo

docker rm -f angulardemo

docker build -t angulardemo .

docker run --name angulardemo --restart=always -d  -p 4200:4200   angulardemo 

kubelet delete -f 01-angulardemo.dpm.yml

kubelet apply -f 01-angulardemo.dpm.yml

