#!/bin/sh

## npm config set registry https://registry.npm.taobao.org  
## npm uninstall -g angular-cli  
## npm cache clean  --force
## yum install python
## npm install -g typescript typings 
## npm install -g @anguluar/cli

git pull


docker build -t docker.registry.cscloud.com/sso-client:1.0 .

docker push docker.registry.cscloud.com/sso-client:1.0

docker rmi docker.registry.cscloud.com/sso-client:1.0 

ansible -i ./ansible-hosts k8s-ms -m command -a 'docker rmi -f docker.registry.cscloud.com/sso-client:1.0'


kubectl delete configmap sso-client-configmap -n test
  
kubectl create configmap sso-client-configmap --namespace=test --from-file=./keycloak.json

kubectl delete -f ./01-sso-client.dpm.yml

kubectl apply -f ./01-sso-client.dpm.yml