#!/bin/sh

## npm config set registry https://registry.npm.taobao.org  
## npm uninstall -g angular-cli  
## npm cache clean  --force
## yum install python
## npm install -g typescript typings 
## npm install -g @anguluar/cli

git pull

docker build -t docker.registry.cscloud.com/angulardemo .

docker push docker.registry.cscloud.com/angulardemo

docker rmi -f docker.registry.cscloud.com/angulardemo  

kubectl delete -f 01-angulardemo.dpm.yml

kubectl apply -f 01-angulardemo.dpm.yml

